### ISSUE TITLE
Noob question: why keep *.ts in demo\wwwroot\app...

### ISSUE THREAD

**Issue by dsaf** [FabianGosebrink/ASPNET-Core-Angular2-StarterTemplate#6]
...as opposed to copying the output (\*.css, \*.html, \*.js) via Gulp from ```demo\app\*.ts```?

Thanks!

**Comment by FabianGosebrink** [comment]
Hey @dsaf - sorry for the long delayed answer but here it is: As this is just for demo purposes right now the developing and the output is in the wwwroot-folder. I have a task on my list to get everything out of it and only have the distribution-files into the wwwroot-folder (as it is in my https://github.com/FabianGosebrink/ASPNET-Core-Angular2-Webpack-StarterTemplate project btw.)
 BR Fabian
PS: There are no noob questions ;)

**Comment by dsaf** [comment]
To be honest, this approach has it's merits. Gulping files into wwwroot causes issues with TFS for me. Generally it feels like doing a work of compiler/linker. I wish wwwroot was treated just like bin - invisible and temporary.

Yes, I have seen your other repos - very helpful stuff! I am trying to stick to mainstream basics for now - no WebPack/PostCSS etc. Maybe I should just wait two years for some C#+XAML->WebAssembly+Canvas stuff :).

**Comment by FabianGosebrink** [comment]
Just moved the develop-folder outside the wwwroot. Still do not know what you mean with the `demo\app\*.ts` folder but maybe this answer for this :)

BR

**Comment by dsaf** [comment]
Yes, this is what I meant :). Thanks! By the way, do you use VS Code and do you ever live debug TS code in VS?

**Comment by FabianGosebrink** [comment]
I use VS Code to develop and debug TS in Chrome.
